export interface Currency {
  code: string;
  name: string;
  symbol: string;
  decimalPlaces: number;
}

export const CURRENCIES: Currency[] = [
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", decimalPlaces: 2 },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", decimalPlaces: 2 },
  { code: "ALL", name: "Albanian Lek", symbol: "L", decimalPlaces: 2 },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", decimalPlaces: 2 },
  { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", decimalPlaces: 2 },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", decimalPlaces: 2 },
  { code: "ARS", name: "Argentine Peso", symbol: "$", decimalPlaces: 2 },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", decimalPlaces: 2 },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ", decimalPlaces: 2 },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", decimalPlaces: 2 },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM", decimalPlaces: 2 },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$", decimalPlaces: 2 },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", decimalPlaces: 2 },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", decimalPlaces: 2 },
  { code: "BHD", name: "Bahraini Dinar", symbol: "BD", decimalPlaces: 3 },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", decimalPlaces: 0 },
  { code: "BMD", name: "Bermudian Dollar", symbol: "$", decimalPlaces: 2 },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", decimalPlaces: 2 },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", decimalPlaces: 2 },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", decimalPlaces: 2 },
  { code: "BSD", name: "Bahamian Dollar", symbol: "$", decimalPlaces: 2 },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", decimalPlaces: 2 },
  { code: "BWP", name: "Botswanan Pula", symbol: "P", decimalPlaces: 2 },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", decimalPlaces: 2 },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", decimalPlaces: 2 },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", decimalPlaces: 2 },
  { code: "CDF", name: "Congolese Franc", symbol: "FC", decimalPlaces: 2 },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", decimalPlaces: 2 },
  { code: "CLP", name: "Chilean Peso", symbol: "$", decimalPlaces: 0 },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", decimalPlaces: 2 },
  { code: "COP", name: "Colombian Peso", symbol: "$", decimalPlaces: 2 },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", decimalPlaces: 2 },
  { code: "CUP", name: "Cuban Peso", symbol: "₱", decimalPlaces: 2 },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "Esc", decimalPlaces: 2 },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", decimalPlaces: 2 },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", decimalPlaces: 0 },
  { code: "DKK", name: "Danish Krone", symbol: "kr", decimalPlaces: 2 },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", decimalPlaces: 2 },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", decimalPlaces: 2 },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£", decimalPlaces: 2 },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", decimalPlaces: 2 },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", decimalPlaces: 2 },
  { code: "EUR", name: "Euro", symbol: "€", decimalPlaces: 2 },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", decimalPlaces: 2 },
  { code: "FKP", name: "Falkland Islands Pound", symbol: "£", decimalPlaces: 2 },
  { code: "GBP", name: "British Pound Sterling", symbol: "£", decimalPlaces: 2 },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", decimalPlaces: 2 },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "GH₵", decimalPlaces: 2 },
  { code: "GIP", name: "Gibraltar Pound", symbol: "£", decimalPlaces: 2 },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", decimalPlaces: 2 },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", decimalPlaces: 0 },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", decimalPlaces: 2 },
  { code: "GYD", name: "Guyanaese Dollar", symbol: "GY$", decimalPlaces: 2 },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", decimalPlaces: 2 },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", decimalPlaces: 2 },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", decimalPlaces: 2 },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", decimalPlaces: 2 },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", decimalPlaces: 2 },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", decimalPlaces: 2 },
  { code: "ILS", name: "Israeli New Sheqel", symbol: "₪", decimalPlaces: 2 },
  { code: "INR", name: "Indian Rupee", symbol: "₹", decimalPlaces: 2 },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", decimalPlaces: 3 },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", decimalPlaces: 2 },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr", decimalPlaces: 0 },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", decimalPlaces: 2 },
  { code: "JOD", name: "Jordanian Dinar", symbol: "JD", decimalPlaces: 3 },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", decimalPlaces: 0 },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", decimalPlaces: 2 },
  { code: "KGS", name: "Kyrgystani Som", symbol: "сом", decimalPlaces: 2 },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", decimalPlaces: 2 },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", decimalPlaces: 0 },
  { code: "KPW", name: "North Korean Won", symbol: "₩", decimalPlaces: 2 },
  { code: "KRW", name: "South Korean Won", symbol: "₩", decimalPlaces: 0 },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", decimalPlaces: 3 },
  { code: "KYD", name: "Cayman Islands Dollar", symbol: "CI$", decimalPlaces: 2 },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", decimalPlaces: 2 },
  { code: "LAK", name: "Laotian Kip", symbol: "₭", decimalPlaces: 2 },
  { code: "LBP", name: "Lebanese Pound", symbol: "L£", decimalPlaces: 2 },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", decimalPlaces: 2 },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$", decimalPlaces: 2 },
  { code: "LSL", name: "Lesotho Loti", symbol: "M", decimalPlaces: 2 },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", decimalPlaces: 3 },
  { code: "MAD", name: "Moroccan Dirham", symbol: "MAD", decimalPlaces: 2 },
  { code: "MDL", name: "Moldovan Leu", symbol: "MDL", decimalPlaces: 2 },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", decimalPlaces: 2 },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", decimalPlaces: 2 },
  { code: "MMK", name: "Myanma Kyat", symbol: "K", decimalPlaces: 2 },
  { code: "MNT", name: "Mongolian Tugrik", symbol: "₮", decimalPlaces: 2 },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", decimalPlaces: 2 },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "MRU", decimalPlaces: 2 },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", decimalPlaces: 2 },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", decimalPlaces: 2 },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", decimalPlaces: 2 },
  { code: "MXN", name: "Mexican Peso", symbol: "Mex$", decimalPlaces: 2 },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", decimalPlaces: 2 },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT", decimalPlaces: 2 },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$", decimalPlaces: 2 },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", decimalPlaces: 2 },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", decimalPlaces: 2 },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", decimalPlaces: 2 },
  { code: "NPR", name: "Nepalese Rupee", symbol: "Rs", decimalPlaces: 2 },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", decimalPlaces: 2 },
  { code: "OMR", name: "Omani Rial", symbol: "﷼", decimalPlaces: 3 },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", decimalPlaces: 2 },
  { code: "PEN", name: "Peruvian Nuevo Sol", symbol: "S/.", decimalPlaces: 2 },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", decimalPlaces: 2 },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", decimalPlaces: 2 },
  { code: "PKR", name: "Pakistani Rupee", symbol: "Rs", decimalPlaces: 2 },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", decimalPlaces: 2 },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲", decimalPlaces: 0 },
  { code: "QAR", name: "Qatari Rial", symbol: "﷼", decimalPlaces: 2 },
  { code: "RON", name: "Romanian Leu", symbol: "lei", decimalPlaces: 2 },
  { code: "RSD", name: "Serbian Dinar", symbol: "din", decimalPlaces: 2 },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", decimalPlaces: 2 },
  { code: "RWF", name: "Rwandan Franc", symbol: "RF", decimalPlaces: 0 },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", decimalPlaces: 2 },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", decimalPlaces: 2 },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", decimalPlaces: 2 },
  { code: "SDG", name: "Sudanese Pound", symbol: "SD", decimalPlaces: 2 },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", decimalPlaces: 2 },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", decimalPlaces: 2 },
  { code: "SHP", name: "Saint Helena Pound", symbol: "£", decimalPlaces: 2 },
  { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le", decimalPlaces: 2 },
  { code: "SOS", name: "Somali Shilling", symbol: "S", decimalPlaces: 2 },
  { code: "SRD", name: "Surinamese Dollar", symbol: "SRD", decimalPlaces: 2 },
  { code: "SSP", name: "South Sudanese Pound", symbol: "SSP", decimalPlaces: 2 },
  { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db", decimalPlaces: 2 },
  { code: "SYP", name: "Syrian Pound", symbol: "£S", decimalPlaces: 2 },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "E", decimalPlaces: 2 },
  { code: "THB", name: "Thai Baht", symbol: "฿", decimalPlaces: 2 },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", decimalPlaces: 2 },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "T", decimalPlaces: 2 },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", decimalPlaces: 3 },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", decimalPlaces: 2 },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", decimalPlaces: 2 },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$", decimalPlaces: 2 },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", decimalPlaces: 2 },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", decimalPlaces: 2 },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", decimalPlaces: 2 },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", decimalPlaces: 0 },
  { code: "USD", name: "US Dollar", symbol: "$", decimalPlaces: 2 },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", decimalPlaces: 2 },
  { code: "UZS", name: "Uzbekistan Som", symbol: "сўм", decimalPlaces: 2 },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs.S", decimalPlaces: 2 },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", decimalPlaces: 0 },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", decimalPlaces: 0 },
  { code: "WST", name: "Samoan Tala", symbol: "WS$", decimalPlaces: 2 },
  { code: "XAF", name: "CFA Franc BEAC", symbol: "FCFA", decimalPlaces: 0 },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$", decimalPlaces: 2 },
  { code: "XOF", name: "CFA Franc BCEAO", symbol: "CFA", decimalPlaces: 0 },
  { code: "XPF", name: "CFP Franc", symbol: "₣", decimalPlaces: 0 },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", decimalPlaces: 2 },
  { code: "ZAR", name: "South African Rand", symbol: "R", decimalPlaces: 2 },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", decimalPlaces: 2 },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$", decimalPlaces: 2 },
];

export const CURRENCIES_BY_CODE: Record<string, Currency> = Object.fromEntries(
  CURRENCIES.map((c) => [c.code, c]),
);

export function getCurrency(code: string): Currency | undefined {
  return CURRENCIES_BY_CODE[code];
}

export function formatPrice(amountUsd: number, currencyCode: string): string {
  const currency = getCurrency(currencyCode);
  if (!currency) return `$${amountUsd.toFixed(2)}`;

  const converted = convertCurrency(amountUsd, currencyCode);
  const formatted = converted.toFixed(currency.decimalPlaces);
  const needsSpace = /^[$€£¥₹₽₩₳₴₸₮₼₲฿]/.test(currency.symbol);
  return needsSpace ? `${currency.symbol} ${formatted}` : `${currency.symbol}${formatted}`;
}

export function convertCurrency(amountUsd: number, toCurrency: string): number {
  if (toCurrency === "USD") return amountUsd;
  const rate = EXCHANGE_RATES[toCurrency];
  if (!rate) return amountUsd;
  return amountUsd * rate;
}

const EXCHANGE_RATES: Record<string, number> = {
  AED: 3.6725,
  AFN: 71.5,
  ALL: 92.5,
  AMD: 388,
  ANG: 1.79,
  AOA: 832,
  ARS: 350,
  AUD: 1.53,
  AWG: 1.79,
  AZN: 1.7,
  BAM: 1.8,
  BBD: 2,
  BDT: 110,
  BGN: 1.8,
  BHD: 0.376,
  BIF: 2850,
  BMD: 1,
  BND: 1.34,
  BOB: 6.91,
  BRL: 4.97,
  BSD: 1,
  BTN: 83.1,
  BWP: 13.6,
  BYN: 3.2,
  BZD: 2,
  CAD: 1.36,
  CDF: 2540,
  CHF: 0.88,
  CLP: 880,
  CNY: 7.24,
  COP: 3950,
  CRC: 520,
  CUP: 24,
  CVE: 94,
  CZK: 22.5,
  DJF: 177,
  DKK: 6.87,
  DOP: 56,
  DZD: 135,
  EGP: 30.9,
  ERN: 15,
  ETB: 56,
  EUR: 0.92,
  FJD: 2.23,
  FKP: 0.79,
  GBP: 0.79,
  GEL: 2.65,
  GHS: 12,
  GIP: 0.79,
  GMD: 64,
  GNF: 8580,
  GTQ: 7.8,
  GYD: 209,
  HKD: 7.82,
  HNL: 24.7,
  HRK: 6.87,
  HTG: 132,
  HUF: 355,
  IDR: 15450,
  ILS: 3.67,
  INR: 83.1,
  IQD: 1460,
  IRR: 42000,
  ISK: 137,
  JMD: 156,
  JOD: 0.709,
  JPY: 149,
  KES: 153,
  KGS: 89,
  KHR: 4080,
  KMF: 448,
  KPW: 900,
  KRW: 1320,
  KWD: 0.307,
  KYD: 0.83,
  KZT: 460,
  LAK: 20500,
  LBP: 15000,
  LKR: 312,
  LRD: 192,
  LSL: 18.8,
  LYD: 4.82,
  MAD: 10,
  MDL: 18,
  MGA: 4500,
  MKD: 56.5,
  MMK: 2100,
  MNT: 3430,
  MOP: 8.05,
  MRU: 39.5,
  MUR: 45,
  MVR: 15.4,
  MWK: 1030,
  MXN: 17.1,
  MYR: 4.68,
  MZN: 63.8,
  NAD: 18.8,
  NGN: 780,
  NIO: 36.6,
  NOK: 10.7,
  NPR: 111,
  NZD: 1.64,
  OMR: 0.384,
  PAB: 1,
  PEN: 3.72,
  PGK: 3.9,
  PHP: 56,
  PKR: 285,
  PLN: 4.02,
  PYG: 7300,
  QAR: 3.64,
  RON: 4.57,
  RSD: 108,
  RUB: 91,
  RWF: 1280,
  SAR: 3.75,
  SBD: 8.3,
  SCR: 14.5,
  SDG: 600,
  SEK: 10.4,
  SGD: 1.34,
  SHP: 0.79,
  SLL: 20900,
  SOS: 568,
  SRD: 37,
  SSP: 4300,
  STN: 22.5,
  SYP: 2500,
  SZL: 18.8,
  THB: 35.5,
  TJS: 10.9,
  TMT: 3.5,
  TND: 3.1,
  TOP: 2.35,
  TRY: 29,
  TTD: 6.76,
  TWD: 31.5,
  TZS: 2500,
  UAH: 38,
  UGX: 3780,
  USD: 1,
  UYU: 39,
  UZS: 12300,
  VES: 36.3,
  VND: 24500,
  VUV: 149,
  WST: 2.7,
  XAF: 600,
  XCD: 2.7,
  XOF: 600,
  XPF: 109,
  YER: 250,
  ZAR: 18.8,
  ZMW: 25,
  ZWL: 322,
};
