-- 0014_rewrite_product_descriptions.sql
-- Rewrites every product description in the 3-sentence style of product 43
-- (Air Fryer), replacing:
--   * imported promo copy ("— promotional offer: X% OFF. Original price was $Y.")
--     scraped from EastMatt/Magunas (migrations 0008/0009), and
--   * terse single-line base descriptions (ids 10-42), and
--   * redundant repetition of the product name inside the description.
--
-- Style (emulated from product 43):
--   1. Benefit hook naming the product once.
--   2. Mechanism/feature with the outcome it delivers.
--   3. "Perfect for ..." use cases.
--
-- No pricing, no discount percentages, no promotional statements.
--
-- Idempotent: backs up products to products_backup_20260807 first, then
-- UPDATEs by primary key, so re-running is safe.

DROP TABLE IF EXISTS products_backup_20260807;
CREATE TABLE products_backup_20260807 AS SELECT * FROM products;

UPDATE products SET description = 'Keep perfect time in timeless style with the Premium Watch. Its automatic movement and sapphire crystal deliver precision and durability you can rely on. Perfect for daily wear, formal occasions, and gifts.' WHERE id = 10;
UPDATE products SET description = 'Carry your essentials in elegant style with the Designer Leather Handbag. Handcrafted from genuine leather with multiple compartments, it keeps your belongings organised and secure. Perfect for work, travel, and everyday outings.' WHERE id = 11;
UPDATE products SET description = 'Immerse yourself in pure sound with the Wireless Headphones. Premium noise-cancelling drivers deliver rich audio for up to 30 hours on a single charge. Perfect for commutes, travel, work, and workouts.' WHERE id = 12;
UPDATE products SET description = 'Make every cup feel special with the Ceramic Coffee Mug. Handmade from smooth ceramic with a minimalist design, it keeps your drink warm and your desk stylish. Perfect for coffee, tea, and warm beverages at home or the office.' WHERE id = 13;
UPDATE products SET description = 'Carry your day with effortless simplicity in the Minimalist Tote Bag. Made from premium cotton with reinforced handles, it holds everything you need without losing its shape. Perfect for shopping, work, beach days, and weekend errands.' WHERE id = 14;
UPDATE products SET description = 'Track your health and stay connected with the Smart Watch Pro. Advanced sensors monitor heart rate and GPS, delivering real-time insights and notifications to your wrist. Perfect for fitness, outdoor adventures, and everyday productivity.' WHERE id = 15;
UPDATE products SET description = 'Brighten your space with the modern Minimalist Lamp. Adjustable brightness lets you switch from focused work to soft ambient light in an instant. Perfect for desks, bedside tables, and reading corners.' WHERE id = 16;
UPDATE products SET description = 'Elevate any outfit with the classic Denim Jacket. Its modern fit and timeless denim finish pair effortlessly with everything you own. Perfect for layering in spring, fall, and cool evenings.' WHERE id = 17;
UPDATE products SET description = 'Practise with confidence on the premium non-slip Yoga Mat. A textured surface grips the floor so you can hold every pose safely, with a carrying strap for easy transport. Perfect for yoga, pilates, stretching, and home workouts.' WHERE id = 18;
UPDATE products SET description = 'Leave a lasting impression with the Luxury Perfume. Notes of jasmine, vanilla, and amber unfold beautifully for a sophisticated scent that lingers all day. Perfect for evenings out, special occasions, and everyday elegance.' WHERE id = 19;
UPDATE products SET description = 'Give your hair the nourishment it craves with the Moisturizing Hair Cream. Its rich formula locks in moisture and tames frizz for soft, manageable strands. Perfect for daily styling, natural curls, and all hair types.' WHERE id = 20;
UPDATE products SET description = 'Restore your hair''s natural vitality with the Hydrating Shampoo. Its gentle cleansing formula removes buildup while replenishing moisture to dry, damaged strands. Perfect for daily use on normal, dry, and colour-treated hair.' WHERE id = 21;
UPDATE products SET description = 'Add body and bounce to your hair with the Volumizing Conditioner. Its lightweight formula detangles and softens while boosting lift at the roots. Perfect for fine, flat hair and everyday conditioning routines.' WHERE id = 22;
UPDATE products SET description = 'Create any look with the complete Professional Makeup Kit. A curated set of eyeshadows, blushes, and lip colours covers everything from subtle to bold. Perfect for everyday wear, events, and professional artists.' WHERE id = 23;
UPDATE products SET description = 'Keep your skin soft and supple with the Nourishing Body Lotion. Enriched with shea butter and essential oils, it delivers deep, long-lasting hydration. Perfect for daily use after showers, before bed, and in dry climates.' WHERE id = 24;
UPDATE products SET description = 'Reveal firmer, younger-looking skin with the Anti-Aging Face Cream. Its advanced formula reduces the appearance of fine lines and boosts elasticity over time. Perfect for daily morning and evening skincare routines.' WHERE id = 25;
UPDATE products SET description = 'Fill your home with warmth and fragrance with the Scented Candle Set. Three premium candles release vanilla, lavender, and sandalwood scents for a calming ambience. Perfect for cosy evenings, relaxation, gifts, and table settings.' WHERE id = 26;
UPDATE products SET description = 'Refresh your living space with the Decorative Throw Pillows. Hand-crafted with modern geometric patterns, they add colour and texture to any sofa or bed. Perfect for living rooms, bedrooms, and accent seating.' WHERE id = 27;
UPDATE products SET description = 'Serve every meal in style with the Ceramic Plate. Handcrafted from durable ceramic with a minimalist finish, it complements both everyday and special dining. Perfect for daily meals, entertaining, and elegant table settings.' WHERE id = 28;
UPDATE products SET description = 'Add timeless elegance to any look with the Gold Pendant Necklace. Crafted in 14k gold-plated finish with a delicate chain, it catches the light beautifully. Perfect for layering, gifting, and special occasions.' WHERE id = 29;
UPDATE products SET description = 'Complete your look with the contemporary Silver Hoop Earrings. Made from sterling silver with a secure clasp, they are lightweight and comfortable all day. Perfect for casual wear, office outfits, and evening events.' WHERE id = 30;
UPDATE products SET description = 'Stack up your style with the Beaded Bracelet Set. Three natural stone bracelets can be worn together or separately for a personalised look. Perfect for casual days, gifting, and layered wrist styling.' WHERE id = 31;
UPDATE products SET description = 'Protect your eyes in style with the Designer Sunglasses. Polarized, UV-protective lenses with a lightweight frame keep your vision clear and comfortable. Perfect for sunny days, driving, and outdoor adventures.' WHERE id = 32;
UPDATE products SET description = 'Train with better alignment on the Premium Yoga Mat. Eco-friendly materials with clear alignment markings help you perfect every pose. Perfect for yoga, pilates, and mindful stretching at home or the studio.' WHERE id = 33;
UPDATE products SET description = 'Build strength anywhere with the Fitness Resistance Bands. Five bands of increasing resistance let you progress safely through every workout. Perfect for home training, travel fitness, and post-injury recovery.' WHERE id = 34;
UPDATE products SET description = 'Stay hydrated all day with the Insulated Water Bottle. Double-wall stainless steel keeps drinks cold for 24 hours or hot for 12. Perfect for gym sessions, hikes, commutes, and the office.' WHERE id = 35;
UPDATE products SET description = 'Get a full workout with the space-saving Adjustable Dumbbell Set. Adjustable weights replace multiple dumbbells, so one compact pair covers every exercise. Perfect for home gyms, small spaces, and progressive strength training.' WHERE id = 36;
UPDATE products SET description = 'Run lighter and faster with the Minimalist Running Shoes. Excellent cushioning and flexibility adapt to every stride for comfort and support. Perfect for daily runs, racing, and long-distance training.' WHERE id = 37;
UPDATE products SET description = 'Step out in timeless style with the Leather Ankle Boots. Premium leather, cushioned insoles, and durable construction offer all-day comfort and support. Perfect for cool weather, casual outfits, and long days on your feet.' WHERE id = 38;
UPDATE products SET description = 'Keep everyday comfort effortless with the Casual Canvas Sneakers. Classic low-top styling with a breathable canvas upper pairs with almost anything. Perfect for weekends, travel, and relaxed daily wear.' WHERE id = 39;
UPDATE products SET description = 'Give your feet a break with the Comfort Slide Sandals. Ergonomic contoured footbeds cushion every step for all-day comfort. Perfect for summer, beach days, and quick errands.' WHERE id = 40;
UPDATE products SET description = 'Upgrade your everyday basics with the Cotton T-Shirt. Soft, breathable cotton with a comfortable fit and reinforced seams keeps its shape wash after wash. Perfect for casual wear, layering, and lounging.' WHERE id = 41;
UPDATE products SET description = 'Stay warm in style with the Wool Sweater. A warm wool-blend knit with classic cable detailing traps heat without the bulk. Perfect for winter days, layering, and cosy evenings.' WHERE id = 42;
UPDATE products SET description = 'Stock your kitchen with the Top Fry Vegetable Oil 10L. Refined for high-heat cooking, it delivers a clean flavour without overpowering your dishes. Perfect for frying, baking, and everyday family meals.' WHERE id = 44;
UPDATE products SET description = 'Keep your pantry ready with the Top Fry Vegetable Oil 3L. Its neutral taste and high smoke point make it a dependable choice for all your cooking. Perfect for frying, stir-frying, and daily meal preparation.' WHERE id = 45;
UPDATE products SET description = 'Fill your kitchen for months with the Top Fry Vegetable Oil 20L. The generous size is ideal for heavy cooking, keeping your favourite recipes light and crisp. Perfect for large households, catering, and deep frying.' WHERE id = 46;
UPDATE products SET description = 'Enjoy fresh-tasting milk any time with Daima ESL Maziwa Bora 450ml. Long-life ESL processing locks in the creamy goodness without needing refrigeration until opened. Perfect for tea, coffee, cereal, and everyday drinking.' WHERE id = 47;
UPDATE products SET description = 'Pour rich, wholesome flavour with Daima Whole Milk ESL 500ml Pouch. The ESL process keeps this full-cream milk fresh longer, with no refrigeration until opened. Perfect for tea, porridge, baking, and daily nutrition.' WHERE id = 48;
UPDATE products SET description = 'Keep creamy milk always on hand with Daima UHT Maziwa Bora 500ml Fino. UHT treatment preserves its rich taste and nutrients without needing a fridge until opened. Perfect for cereals, hot drinks, cooking, and straight sipping.' WHERE id = 49;
UPDATE products SET description = 'Treat yourself to a fruity sip with Daima Strawberry Flavoured Milk 250ml. Creamy milk blended with a sweet strawberry taste makes every gulp refreshing. Perfect for lunchboxes, on-the-go snacks, and kids'' treats.' WHERE id = 50;
UPDATE products SET description = 'Satisfy your chocolate cravings with Daima Chocolate Flavoured Milk 250ml. Rich cocoa meets smooth milk for a delicious, energy-boosting drink. Perfect for lunchboxes, post-workout refuelling, and afternoon treats.' WHERE id = 51;
UPDATE products SET description = 'Enjoy a classic flavour with Daima Vanilla Flavoured Milk 250ml. Smooth, creamy milk infused with sweet vanilla makes every sip comforting. Perfect for lunchboxes, quick snacks, and on-the-go refreshment.' WHERE id = 52;
UPDATE products SET description = 'Stock up on fruity goodness with the Daima Strawberry Flavoured Milk 6-pack. Six creamy bottles deliver the same delicious strawberry taste for the whole family. Perfect for lunchboxes, parties, and weekly snacking.' WHERE id = 53;
UPDATE products SET description = 'Keep the family stocked with the Daima Vanilla Flavoured Milk 6-pack. Six smooth, creamy bottles of classic vanilla make snack time simple. Perfect for lunchboxes, school runs, and fridge essentials.' WHERE id = 54;
UPDATE products SET description = 'Always have a favourite ready with the Daima Chocolate Flavoured Milk 6-pack. Six rich, creamy chocolate bottles please kids and adults alike. Perfect for lunchboxes, parties, and everyday treats.' WHERE id = 55;
UPDATE products SET description = 'Give everyone a choice with the Daima Assorted Flavoured Milk 6-pack. A mix of strawberry, chocolate, and vanilla bottles covers every taste. Perfect for families, gatherings, and variety-loving snackers.' WHERE id = 56;
UPDATE products SET description = 'Bake and cook with confidence using Pembe Wheat Flour 2kg. Finely milled wheat flour gives consistent results for light, fluffy bakes and soft doughs. Perfect for chapati, mandazi, cakes, and everyday bread.' WHERE id = 57;
UPDATE products SET description = 'Serve smooth, hearty ugali with Pembe Maize Meal 2kg. Finely milled from quality maize, it cooks to a perfect, consistent texture every time. Perfect for ugali, porridge, and traditional family meals.' WHERE id = 58;
UPDATE products SET description = 'Keep your family fed with Soko Maize Meal 2kg. Milled from selected maize, it produces smooth, satisfying ugali and porridge. Perfect for everyday meals and traditional Kenyan dishes.' WHERE id = 59;
UPDATE products SET description = 'Make soft, stretchy dough with Pembe Atta Mark Flour 2kg. This fine wheat flour is specially milled for chapati and mandazi that stay tender. Perfect for daily flatbreads, fried doughs, and baking.' WHERE id = 60;
UPDATE products SET description = 'Stock the family staple with Pembe Maize Meal 5kg. The larger pack ensures you always have quality maize meal for smooth, filling meals. Perfect for ugali, porridge, and regular family cooking.' WHERE id = 61;
UPDATE products SET description = 'Feed a large household with Pembe Maize Meal 10kg. This bulk pack keeps your pantry stocked with fine maize meal for weeks of cooking. Perfect for ugali, porridge, and big family gatherings.' WHERE id = 62;
UPDATE products SET description = 'Start the day with a nourishing tradition using Soko Uji Wimbi Mix Sour 1kg. The fermented finger-millet blend gives a rich, naturally sour porridge. Perfect for breakfast, children, and wholesome family meals.' WHERE id = 63;
UPDATE products SET description = 'Enjoy dependable quality with Two Ten Maize Meal 2kg. Smooth milling and consistent texture make it a trusted choice for everyday cooking. Perfect for ugali, porridge, and traditional meals.' WHERE id = 64;
UPDATE products SET description = 'Make every meal satisfying with Amaize Premium Maize Meal 2kg. Premium milling delivers a smooth, fine texture for perfect ugali every time. Perfect for family dinners, porridge, and daily cooking.' WHERE id = 65;
UPDATE products SET description = 'Serve fragrant, fluffy rice with Pearl Pishori Rice 2kg. Premium pishori grains cook up light and separate with an irresistible aroma. Perfect for pilau, biryani, and everyday rice dishes.' WHERE id = 66;
UPDATE products SET description = 'Keep your rice supply ready with Pearl Pishori Rice 5kg. Long, aromatic grains stay fluffy and separate, making every meal special. Perfect for pilau, biryani, rice dishes, and family dinners.' WHERE id = 67;
UPDATE products SET description = 'Cook light, non-sticky rice with Daawat Long Grain Rice 5kg. Premium long grains hold their shape and fluff beautifully on the stove. Perfect for stir-fries, rice bowls, and everyday sides.' WHERE id = 68;
UPDATE products SET description = 'Bring authentic aroma to your table with Daawat Traditional Basmati Rice 5kg. Aged basmati grains elongate into separate, fragrant servings. Perfect for biryani, pilau, and festive meals.' WHERE id = 69;
UPDATE products SET description = 'Cook wholesome, protein-rich meals with Pearl Green Gram Polished 1kg. Clean, polished green grams soften quickly for soups and stews. Perfect for curries, dhal, and healthy everyday dishes.' WHERE id = 70;
UPDATE products SET description = 'Get dependable everyday rice with C.I.L Blended Rice 2kg. A well-balanced blend cooks into fluffy, separate grains with a mild taste. Perfect for family meals, rice bowls, and daily cooking.' WHERE id = 71;
UPDATE products SET description = 'Make a quick, satisfying dinner with Ranee Standard Spaghetti 400g. Quality durum wheat pasta cooks al dente and holds sauce beautifully. Perfect for bolognese, pasta salads, and midweek meals.' WHERE id = 72;
UPDATE products SET description = 'Serve restaurant-style rice at home with Pearl Super Basmati Rice 2kg. Super-long grains with a delicate aroma cook into fluffy perfection. Perfect for biryani, pilau, and special occasions.' WHERE id = 73;
UPDATE products SET description = 'Give your mornings a boost with Nuvita Vitamilk 200g. Fortified with vitamins and minerals, this crunchy cereal delivers energy and nutrition. Perfect for breakfast, kids, and quick snack bowls.' WHERE id = 74;
UPDATE products SET description = 'Grab a simple, satisfying bite with Bravo G Biscuit 200g. Golden, crisp biscuits offer the classic tea-time taste everyone loves. Perfect for tea breaks, lunchboxes, and afternoon snacking.' WHERE id = 75;
UPDATE products SET description = 'Warm up snack time with Nuvita Crunchy Ginger Biscuits 200g. A crisp texture with a gentle ginger kick makes every bite moreish. Perfect for tea, coffee, and cosy breaks.' WHERE id = 76;
UPDATE products SET description = 'Start the day golden with M.Harvest Cornflakes 500g. Light, crispy flakes made from quality maize stay crunchy in milk. Perfect for breakfast, kids, and quick morning bowls.' WHERE id = 77;
UPDATE products SET description = 'Enjoy a two-in-one treat with H.O.Manji Duos Biscuit 60g. Crisp biscuit layers with a creamy filling make every bite delicious. Perfect for lunchboxes, tea time, and on-the-go snacks.' WHERE id = 78;
UPDATE products SET description = 'Keep breakfast simple with M.Harvest Cornflakes 250g pouch. The same golden, crunchy flakes in a handy smaller pack. Perfect for single servings, lunchboxes, and kids'' bowls.' WHERE id = 79;
UPDATE products SET description = 'Turn breakfast into a treat with M.Harvest Choco Rice 250g pouch. Chocolatey, crisp rice puffs make a fun, crunchy start to the day. Perfect for kids, cereal bowls, and quick snacks.' WHERE id = 80;
UPDATE products SET description = 'Make cereal time fun with M.Harvest Choco Shells 250g pouch. Crispy chocolate-coated shells bring a cocoa crunch to every bowl. Perfect for kids'' breakfasts and sweet snack time.' WHERE id = 81;
UPDATE products SET description = 'Treat yourself to buttery comfort with Golden Shortcake Biscuit 200g. Classic shortcake crumbles softly with a rich, buttery flavour. Perfect for tea, coffee, and quiet moments.' WHERE id = 82;
UPDATE products SET description = 'Enjoy a wholesome classic with Golden Digestive Classic Biscuits 200g. Lightly sweet wholegrain biscuits are perfect for dunking. Perfect for tea time, lunchboxes, and everyday snacking.' WHERE id = 83;
UPDATE products SET description = 'Keep a handy snack at reach with Golden Digestive Classic Biscuits 100g. The same wholesome wholegrain crunch in a single-serve pack. Perfect for lunchboxes, tea breaks, and on-the-go.' WHERE id = 84;
UPDATE products SET description = 'Indulge in nutty goodness with Golden Cashew Cookies 200g. Real cashew pieces baked into golden cookies for a rich, satisfying crunch. Perfect for tea, coffee, and dessert moments.' WHERE id = 85;
UPDATE products SET description = 'Satisfy sweet cravings with Golden Choc Chips Cookies 200g. Generous chocolate chips melt into every golden, chewy bite. Perfect for tea time, lunchboxes, and treats.' WHERE id = 86;
UPDATE products SET description = 'Enjoy a classic pairing with Golden Peanut Cookies 200g. Roasted peanut pieces add crunch and rich flavour to buttery cookies. Perfect for tea breaks, snacking, and sharing.' WHERE id = 87;
UPDATE products SET description = 'Delight in smooth buttery flavour with Golden Butter Cookies 200g. These crisp, golden cookies are baked to melt-in-the-mouth perfection. Perfect for tea time, gifting, and special treats.' WHERE id = 88;
UPDATE products SET description = 'Add a tropical twist with Golden Coconut Cookies 200g. Toasted coconut gives every bite a sweet, chewy crunch. Perfect for tea, coffee, and cosy breaks.' WHERE id = 89;
UPDATE products SET description = 'Spread creamy, family-favourite taste with Blue Band Original 500g. Rich margarine spreads smoothly and works beautifully in baking. Perfect for toast, chapati, sandwiches, and cooking.' WHERE id = 90;
UPDATE products SET description = 'Sweeten your mornings with Kenylon Strawberry Jam 500g. Real strawberry flavour in a smooth, spreadable preserve the whole family loves. Perfect for toast, pancakes, pastries, and baking.' WHERE id = 91;
UPDATE products SET description = 'Cook with reliability anywhere with the Mika Gas Stove 1 Burner. A compact single burner with steady flame control suits small kitchens and outdoor use. Perfect for apartments, camping, and backup cooking.' WHERE id = 92;
UPDATE products SET description = 'Keep your devices powered with Eveready Heavy Duty Red AA Batteries. Four dependable batteries deliver lasting energy for everyday electronics. Perfect for remotes, torches, toys, and clocks.' WHERE id = 93;
UPDATE products SET description = 'Keep your family''s food fresh with the Mika Fridge 255L 2-Door. Spacious cooling with adjustable shelves preserves freshness and organises everything. Perfect for households, weekly shopping, and everyday storage.' WHERE id = 94;
UPDATE products SET description = 'Cook faster and smarter with the Mika Gas Stove Table Top MGS1401. Multiple burners with precise flame control make meal preparation effortless. Perfect for family kitchens, flats, and daily cooking.' WHERE id = 95;
UPDATE products SET description = 'Fry light and crispy with Fresh Fri Cooking Oil 3L. Refined for high-heat cooking, it keeps flavours clean and food golden. Perfect for frying, stir-frying, and everyday meals.' WHERE id = 96;
UPDATE products SET description = 'Quench your thirst naturally with Delmonte Juice 1L. Real fruit juice delivers refreshing taste in your favourite flavours. Perfect for breakfast, lunchboxes, and family meals.' WHERE id = 97;
UPDATE products SET description = 'Refresh after every workout with Hobby Men Bodywash and Shampoo Sport 400ml. The energising formula cleanses body and hair while cooling tired muscles. Perfect for the gym, sports days, and daily showers.' WHERE id = 98;
UPDATE products SET description = 'Enjoy a smooth, mellow finish with Chrome Brandy 750ml. A refined brandy with rich notes crafted for sipping and mixing alike. Perfect for celebrations, cocktails, and cosy evenings.' WHERE id = 99;
UPDATE products SET description = 'Chill out with Cipi G&T Ready-to-Drink Spiced Orange. A crisp, sparkling gin and tonic with a warming spiced orange twist. Perfect for parties, sunny afternoons, and easy entertaining.' WHERE id = 100;
UPDATE products SET description = 'Discover a fresh take on Scotch with Johnnie Walker Blonde 750ml. Honeyed, light whisky balanced with citrus and vanilla for easy drinking. Perfect for cocktails, toasts, and relaxed evenings.' WHERE id = 101;
UPDATE products SET description = 'Try a bold flavour pairing with K.O Mango and Chilli Cider 330ml. Sweet mango meets a gentle chilli kick in a crisp, sparkling cider. Perfect for adventurous palates, parties, and warm days.' WHERE id = 102;
UPDATE products SET description = 'Refresh with crisp, classic taste in K.O Apple Dry Cider 330ml. Dry apple cider balances tartness with a clean, sparkling finish. Perfect for gatherings, summer drinks, and easy refreshment.' WHERE id = 103;
UPDATE products SET description = 'Heat and cook in minutes with the Von Microwave Black 20L. Even, efficient heating with simple controls handles reheating and defrosting easily. Perfect for busy kitchens, offices, and quick meals.' WHERE id = 104;
UPDATE products SET description = 'Iron creases away effortlessly with the Von Steam Iron Ceramic. A ceramic soleplate glides smoothly while powerful steam lifts wrinkles fast. Perfect for shirts, workwear, and family laundry.' WHERE id = 105;
UPDATE products SET description = 'Blend smoothies and soups in seconds with the Von Blender White. A powerful motor and sharp blades puree everything from fruit to ice. Perfect for breakfasts, juices, sauces, and family cooking.' WHERE id = 106;
UPDATE products SET description = 'Enjoy instant hot water with the Von Electric Black Water Dispenser. Fast heating delivers hot water on demand for drinks and cooking. Perfect for homes, offices, tea, coffee, and instant meals.' WHERE id = 107;
UPDATE products SET description = 'Cleanse hands gently with Brio Antibacterial Handwash Truly Natural 500ml. Naturally derived antibacterial formula removes germs without drying skin. Perfect for bathrooms, kitchens, and everyday hygiene.' WHERE id = 108;
UPDATE products SET description = 'Safeguard your appliances with the 7amps Fridge Protector. It stabilises voltage to shield refrigerators and electronics from surges. Perfect for homes with unstable power, fridges, and TVs.' WHERE id = 109;
UPDATE products SET description = 'Bring the cinema home with the Ailyons Smart TV 55-inch. Stunning picture quality with built-in streaming for endless entertainment. Perfect for family nights, movies, sports, and gaming.' WHERE id = 110;
UPDATE products SET description = 'Fill any room with rich sound using the Ailyons Multimedia Speaker. Clear, powerful audio connects easily to your favourite devices. Perfect for music, movies, parties, and everyday listening.' WHERE id = 111;
UPDATE products SET description = 'Wipe up messes sustainably with Velvex Eco Kitchen Towel Twin Pack. Strong, absorbent sheets handle spills and daily cleanup. Perfect for kitchens, wiping, and household tasks.' WHERE id = 112;
UPDATE products SET description = 'Stay comfortable and protected with Always Ultra Thin Long Duo 12x16. Ultra-thin design absorbs quickly while you stay dry and confident. Perfect for daily protection, active days, and overnight wear.' WHERE id = 113;
UPDATE products SET description = 'Keep your baby fresh and clean with Bella Baby Wipes 80''s. Soft, gentle wipes clean up messes without irritating delicate skin. Perfect for nappy changes, hands and face, and outings.' WHERE id = 114;
UPDATE products SET description = 'Enjoy crisp, pure refreshment with Orchid Valley Pure Apple Juice 1L. Made from real apples with no added sugar for honest, fruity taste. Perfect for breakfast, lunchboxes, and family drinks.' WHERE id = 115;
UPDATE products SET description = 'Sip something sparkling and healthy with Booch Passion and Baobab. Fermented tea with tangy passion fruit and baobab makes a refreshing treat. Perfect for wellness routines, afternoons, and mindful refreshment.' WHERE id = 116;
UPDATE products SET description = 'Serve a hearty, comforting meal with Kenylon Baked Beans Tomato Sauce 420g. Tender beans simmered in rich tomato sauce are ready in minutes. Perfect for breakfast, toast, stews, and family dinners.' WHERE id = 117;
UPDATE products SET description = 'Add sweet, golden corn to any dish with Kenylon Corn Off The Cob 400g. Sweet kernels are ready to cook straight from the tin. Perfect for salads, stews, soups, and side dishes.' WHERE id = 118;
UPDATE products SET description = 'Deepen the flavour of your cooking with Kenylon Tomato Paste 450g. Concentrated tomato paste adds rich colour and taste to any recipe. Perfect for stews, sauces, curries, and soups.' WHERE id = 119;
UPDATE products SET description = 'Cook wholesome meals with Daawat Green Gram 1kg. Clean, high-quality green grams cook up tender and protein-rich. Perfect for dhal, soups, curries, and healthy bowls.' WHERE id = 120;
UPDATE products SET description = 'Spread rich fruity sweetness with Kenylon Red Plum Jam 500g. Real plum flavour in a smooth, glossy preserve. Perfect for toast, pancakes, pastries, and baking.' WHERE id = 121;
UPDATE products SET description = 'Keep your home fresh and clean with Soft Lavender 2L. Multi-purpose detergent with a calming lavender scent lifts dirt and stains. Perfect for laundry, floors, dishes, and household cleaning.' WHERE id = 122;
UPDATE products SET description = 'Cleanse and refresh hands with Fields of Africa Handwash Raspberry 500ml. Gentle, moisturising formula with a fruity raspberry fragrance. Perfect for bathrooms, kitchens, and daily hand care.' WHERE id = 123;
UPDATE products SET description = 'Whiten, disinfect, and deodorise with Topex Bleach Regular 2.25L. A powerful bleach formula kills germs and removes stains across the home. Perfect for laundry, bathrooms, kitchens, and surfaces.' WHERE id = 124;
UPDATE products SET description = 'Protect your colours while you clean with Topex Bleach Colours 2.25L. Colour-safe bleach whitens and disinfects without fading fabrics. Perfect for coloured laundry, bathrooms, and household surfaces.' WHERE id = 125;
UPDATE products SET description = 'Cook fluffy, non-sticky rice every time with CIL Pure Long Grain White Rice 5kg. Premium long grains stay separate and light after cooking. Perfect for everyday meals, rice bowls, and side dishes.' WHERE id = 126;
UPDATE products SET description = 'Fill your kitchen with fragrance with Daawat Aromatic Rice 5kg. Long aromatic grains cook into soft, separate, flavourful rice. Perfect for biryani, pilau, and family meals.' WHERE id = 127;
UPDATE products SET description = 'Serve an authentic feast with Daawat Traditional Basmati Rice 5kg. Aged basmati grains cook into extra-long, fluffy, fragrant servings. Perfect for biryani, pilau, and festive occasions.' WHERE id = 128;
UPDATE products SET description = 'Cook premium rice for every celebration with Pearl Super Basmati Rice 5kg. Super-long grains with a delicate aroma fluff up beautifully. Perfect for biryani, pilau, and large family dinners.' WHERE id = 129;
UPDATE products SET description = 'Create café-style foam at home with the Mika Milk Frother Cordless. It whips hot or cold milk into silky foam in seconds. Perfect for lattes, cappuccinos, hot chocolate, and matcha.' WHERE id = 130;
UPDATE products SET description = 'Stay cool and comfortable with the Mika Stand Fan 16-inch. Strong, adjustable airflow circulates the room with quiet, steady operation. Perfect for bedrooms, living rooms, offices, and hot days.' WHERE id = 131;
UPDATE products SET description = 'Enjoy instant hot and cold water with the Mika Free-standing Water Dispenser. A convenient free-standing design delivers water at your preferred temperature. Perfect for homes, offices, and busy households.' WHERE id = 132;
UPDATE products SET description = 'Brew rich, full-bodied coffee with the Manual Coffee Maker Black and Silver. A classic manual design gives you complete control over every cup. Perfect for filter coffee, mornings, and coffee lovers.' WHERE id = 133;
UPDATE products SET description = 'Enjoy fresh, creamy taste with Tuzo Whole Milk Pouch 450ml ESL. Long-life ESL processing keeps this whole milk delicious without refrigeration until opened. Perfect for tea, cereal, baking, and everyday drinking.' WHERE id = 134;
UPDATE products SET description = 'Start the day light and crunchy with M.Harvest Flakes 500g. Golden wholegrain flakes stay crisp in milk for a satisfying breakfast. Perfect for mornings, kids, and quick cereal bowls.' WHERE id = 135;
UPDATE products SET description = 'Keep breakfast simple with M.Harvest Cornflakes 250g bag. The same golden, crunchy flakes in a handy smaller pack. Perfect for single servings, lunchboxes, and everyday mornings.' WHERE id = 136;
UPDATE products SET description = 'Create rich, savoury stews with Oyo Beef Mchuzi Mix. A ready blend of spices gives your beef a deep, delicious flavour. Perfect for beef stew, pilau, and hearty family dinners.' WHERE id = 137;
UPDATE products SET description = 'Fill the bowl with cocoa goodness using Temmy''s Choco Pillow 375g. Crispy cereal pillows with a chocolate centre add fun to breakfast. Perfect for kids, cereal mixes, and sweet snacks.' WHERE id = 138;
UPDATE products SET description = 'Colour your morning bowl with Temmy''s Fruit Rings 250g. Crispy, fruity rings bring playful crunch and colour to breakfast. Perfect for kids, cereal bowls, and quick snacks.' WHERE id = 139;
UPDATE products SET description = 'Sweeten everything perfectly with Zesta Caster Sugar 500g. Fine-cast sugar dissolves quickly, ideal for baking and drinks. Perfect for cakes, desserts, tea, coffee, and preserves.' WHERE id = 140;
UPDATE products SET description = 'Enjoy a chocolatey crunch at breakfast with Temmy''s Choco Pops 500g. Crisp chocolate-coated pops make every bowl a treat. Perfect for kids, cereal time, and quick sweet snacks.' WHERE id = 141;
UPDATE products SET description = 'Spread and bake with confidence using Prestige Margarine 1kg. A smooth, creamy margarine that works for cooking and baking alike. Perfect for toast, chapati, cakes, and family meals.' WHERE id = 142;
