-- 0015_migrate_product_images_to_storage.sql
-- Moves product image URLs for products 44-142 from the local `/images/` folder
-- (client/public/images/vendor-batch-a/*.webp and vendor-batch-b/*.webp — served
-- by the Vite dev server / static client build) into the public `products`
-- Supabase Storage bucket under the `vendor-batch-a/` and `vendor-batch-b/`
-- prefixes.
--
-- The 99 WebP files were uploaded to Storage directly (S3 API) before this
-- migration; this script only rewrites the DB `image_url` values to the public
-- object URLs so images keep working after the local folder is deleted.
--
-- Idempotent: backs up products to products_backup_20260807_images first, then
-- UPDATEs by primary key only where image_url still points at /images/, so
-- re-running is safe.

DROP TABLE IF EXISTS products_backup_20260807_images;
CREATE TABLE products_backup_20260807_images AS SELECT * FROM products;

UPDATE products SET image_url = CASE id
  WHEN 44 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/100217.webp'
  WHEN 45 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/100220.webp'
  WHEN 46 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/100274.webp'
  WHEN 47 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/110680.webp'
  WHEN 48 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/110743.webp'
  WHEN 49 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/110976.webp'
  WHEN 50 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/110980.webp'
  WHEN 51 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/110982.webp'
  WHEN 52 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/111005.webp'
  WHEN 53 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/111042.webp'
  WHEN 54 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/111043.webp'
  WHEN 55 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/111044.webp'
  WHEN 56 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/111045.webp'
  WHEN 57 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/120066.webp'
  WHEN 58 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/120068.webp'
  WHEN 59 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/120127.webp'
  WHEN 60 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/120167.webp'
  WHEN 61 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/120178.webp'
  WHEN 62 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/120179.webp'
  WHEN 63 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/120237.webp'
  WHEN 64 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/120335.webp'
  WHEN 65 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/120347.webp'
  WHEN 66 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/130091.webp'
  WHEN 67 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/130251.webp'
  WHEN 68 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/130252.webp'
  WHEN 69 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/130275.webp'
  WHEN 70 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/130444.webp'
  WHEN 71 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/130510.webp'
  WHEN 72 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/130560.webp'
  WHEN 73 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/130563.webp'
  WHEN 74 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/150694.webp'
  WHEN 75 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/150754.webp'
  WHEN 76 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/150819.webp'
  WHEN 77 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/150873.webp'
  WHEN 78 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/151153.webp'
  WHEN 79 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/151330.webp'
  WHEN 80 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/151331.webp'
  WHEN 81 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/151332.webp'
  WHEN 82 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/151363.webp'
  WHEN 83 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/151365.webp'
  WHEN 84 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/151398.webp'
  WHEN 85 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/151401.webp'
  WHEN 86 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/151402.webp'
  WHEN 87 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/151403.webp'
  WHEN 88 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/151404.webp'
  WHEN 89 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/151405.webp'
  WHEN 90 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/170009.webp'
  WHEN 91 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/eastmatt/170061.webp'
  WHEN 92 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295906.webp'
  WHEN 93 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295907.webp'
  WHEN 94 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295908.webp'
  WHEN 95 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295909.webp'
  WHEN 96 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295910.webp'
  WHEN 97 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295911.webp'
  WHEN 98 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295912.webp'
  WHEN 99 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295913.webp'
  WHEN 100 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295914.webp'
  WHEN 101 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295915.webp'
  WHEN 102 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295916.webp'
  WHEN 103 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295917.webp'
  WHEN 104 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295918.webp'
  WHEN 105 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295919.webp'
  WHEN 106 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295920.webp'
  WHEN 107 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295921.webp'
  WHEN 108 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295924.webp'
  WHEN 109 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295925.webp'
  WHEN 110 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295930.webp'
  WHEN 111 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295931.webp'
  WHEN 112 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295932.webp'
  WHEN 113 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295933.webp'
  WHEN 114 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295938.webp'
  WHEN 115 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295939.webp'
  WHEN 116 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295940.webp'
  WHEN 117 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295941.webp'
  WHEN 118 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295942.webp'
  WHEN 119 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295943.webp'
  WHEN 120 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295944.webp'
  WHEN 121 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295945.webp'
  WHEN 122 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295946.webp'
  WHEN 123 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295947.webp'
  WHEN 124 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295948.webp'
  WHEN 125 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295949.webp'
  WHEN 126 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295950.webp'
  WHEN 127 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295951.webp'
  WHEN 128 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295952.webp'
  WHEN 129 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295953.webp'
  WHEN 130 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295954.webp'
  WHEN 131 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295955.webp'
  WHEN 132 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295956.webp'
  WHEN 133 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295957.webp'
  WHEN 134 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295958.webp'
  WHEN 135 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295959.webp'
  WHEN 136 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295960.webp'
  WHEN 137 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295961.webp'
  WHEN 138 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295962.webp'
  WHEN 139 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295963.webp'
  WHEN 140 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295964.webp'
  WHEN 141 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295965.webp'
  WHEN 142 THEN 'https://bdkvujsvyttdzbiwexks.supabase.co/storage/v1/object/public/products/magunas/1000295966.webp'
  ELSE image_url
END
WHERE image_url LIKE '/images/%';
